version: '3'
services:
  yii2-php:
    #image: yiisoftware/yii2-php:7.2-apache
    build: .
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
